#!/usr/bin/env ruby

require 'addzone/master'
require 'fileutils'
require 'optparse'

begin
  mail_server = nil
  opt = OptionParser.new
  Version = AddZone::VERSION
  opt.on("-m mail_server_address") { |v| mail_server = v }
  opt.banner = "Usage: #{opt.program_name} zone_name [ ip_address ]"
  opt.parse!(ARGV)

  if ARGV.size != 2 && ARGV.size != 1
    puts opt
    abort
  end

  add_master = AddZone::Master.new(AddZone::DEFAULT_ADDZONE_CONF_PATH)
  domain = ARGV[0]
  add_master.ip_address = ARGV[1] if ARGV.size == 2
  add_master.mail_server_address = mail_server if mail_server

  puts "Domain   : #{domain}"
  puts "IP Address: #{add_master.ip_address}"
  puts "Mail Server Address: #{add_master.mail_server_address}" if mail_server

  add_master.add_zone(domain)
  add_master.named_checkconf
  add_master.rndc_reload

  add_master.slave_servers.each do |server|
    next unless server['ssh']

    cmd = "ssh #{server['ssh']} #{server['name']} addslave #{domain}"
    puts cmd
    puts `#{cmd}`
  end

  sleep 1

  add_master.name_servers.each do |server|
    AddZone.check_dns(server['name'], domain)
  end

rescue StandardError => e
  abort "ERROR: #{e}"
end
