#!/usr/bin/env ruby

require 'addzone/slave'

begin
  if ARGV.size != 2 && ARGV.size != 1
    print "USAGE: #{$0} example.com [192.168.1.1] \n"
    exit
  end

  domain = ARGV[0]
  add_slave = AddSlave.new("/etc/addzone.conf")

  if ARGV.size == 2
    add_slave.master_ip = ARGV[1]
  end

  puts "Domain   : #{domain}"
  puts "Master IP: #{add_slave.master_ip}"

  add_slave.add_zone(domain)
  add_slave.named_checkconf
  add_slave.rndc_reload

rescue => error
  puts "ERROR: " + error.to_s
end
