#!/usr/bin/env ruby

require 'addzone/slave'
require 'optparse'

begin
  opt = OptionParser.new
  Version = AddZone::VERSION
  opt.banner = "Usage: #{opt.program_name} zone_name [ ip_address ]"
  opt.parse!(ARGV)

  if ARGV.size != 2 && ARGV.size != 1
    puts opt
    abort
  end

  domain = ARGV[0]
  add_slave = AddZone::Slave.new(AddZone::DEFAULT_ADDZONE_CONF_PATH)

  if ARGV.size == 2
    add_slave.master_ip = ARGV[1]
  end

  puts "Zone Name             : #{domain}"
  puts "Master Server Address : #{add_slave.master_ip}"

  add_slave.add_zone(domain)
  add_slave.named_checkconf
  add_slave.rndc_reload

rescue StandardError => e
  puts "ERROR: #{e}"
end
