#!/usr/bin/env ruby

require 'fileutils'
require 'addzone/master'

zone = ARGV[0]
if ARGV.size == 0
  abort "USAGE: #{$0} example.com"
end

class AddZone::DelMaster < AddZone::Master

  def initialize(zone)
    super(AddZone::DEFAULT_ADDZONE_CONF_PATH)
    @zone = zone
  end

end

del = AddZone::DelMaster.new(zone)

del.named_checkconf
del.rndc_status
puts "-"*40
puts del.delete_zone(zone)
puts "-"*40
del.named_checkconf
del.rndc_reload
del.rndc_status

del.slave_servers.each do |server|
  cmd = "ssh -p 10022 #{server['name']} delslave #{zone}"
  puts cmd
  puts `#{cmd}`
end

