#!/usr/bin/env ruby

require 'fileutils'
require 'addzone/master'
require 'optparse'

begin
  opt = OptionParser.new
  Version = AddZone::VERSION
  opt.banner = "Usage: #{opt.program_name} zone_name"
  opt.parse!(ARGV)

  if ARGV.size != 1
    puts opt
    abort
  end

  zone = ARGV[0]

  del = AddZone::Master.new(AddZone::DEFAULT_ADDZONE_CONF_PATH)
  del.named_checkconf
  del.rndc_status
  puts "-" * 40
  puts del.delete_zone(zone)
  puts "-" * 40
  del.named_checkconf
  del.rndc_reload
  del.rndc_status

  del.slave_servers.each do |server|
    sudo_str = if server['sudo']
                 "sudo"
               else
                 ""
               end

    cmd = "ssh #{server['ssh']} #{server['name']} #{sudo_str} delslave #{zone}"
    puts cmd
    puts `#{cmd}`
  end

rescue StandardError => e
  abort "ERROR: #{e}"
end