#!/usr/bin/env ruby

require 'fileutils'
require 'addzone/slave'

if ARGV.size != 1
  abort "USAGE: #{$0} example.com"
end

zone = ARGV[0]

del = AddZone::Slave.new(AddZone::DEFAULT_ADDZONE_CONF_PATH)
del.named_checkconf
del.rndc_status
puts "-"*40
puts del.delete_zone(zone)
puts "-"*40
del.named_checkconf
del.rndc_reload
del.rndc_status
