#!/usr/bin/env ruby

require 'fileutils'
require 'addzone/slave'

zone = ARGV[0]
if ARGV.size == 0
  abort "USAGE: #{$0} example.com"
end

class AddZone::DelSlave < AddZone::Slave

  def initialize(zone)
    super(AddZone::DEFAULT_ADDZONE_CONF_PATH)
    @zone = zone
  end

end

del = AddZone::DelSlave.new(zone)
del.named_checkconf
del.rndc_status
puts "-"*40
puts del.delete_zone(zone)
puts "-"*40
del.named_checkconf
del.rndc_reload
del.rndc_status
